polls/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import polls_list, polls_detail, index, detail, results, vote, IndexView, DetailView, ResultsView
from .apiviews import PollList, PollDetail, ChoiceList, CreateVote, UserCreate, LoginView


from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Polls API')

app_name = 'polls'

'''Pure Django'''
# urlpatterns = [
#     path("polls/", polls_list, name="polls_list"),
#     path("polls/<int:pk>/", polls_detail, name="polls_detail")
# ]

'''DRF APIView and Generic Views'''
urlpatterns = [
    # views
    # path('', index, name='index'),
    # # ex: /5/
    # path('<int:poll_id>/', detail, name='detail'),
    # # ex: /5/results/
    # path('<int:poll_id>/results/', results, name='results'),

    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', ResultsView.as_view(), name='results'),
    # ex: /5/vote/
    path('<int:poll_id>/vote/', vote, name='vote'),

    # apiviews
    path("polls/", PollList.as_view(), name="polls_list"),
    path("polls/<int:pk>/", PollDetail.as_view(), name="polls_detail"),
    # path("choices/", ChoiceList.as_view(), name="choice_list"),  # for create choice and show list
    path("polls/<int:pk>/choices/", ChoiceList.as_view(), name="choice_list"),  # for showing choice list by individual poll
    path("polls/<int:pk>/choices/<int:choice_pk>/vote/", CreateVote.as_view(), name="create_vote"),

    path("users/", UserCreate.as_view(), name="user_create"),
    path("login/", LoginView.as_view(), name="login"),

    path(r'swagger-docs/', schema_view),
]


'''Viewsets and Router'''
# router = DefaultRouter()
# router.register('polls', PollViewSet, basename='polls')
#
# urlpatterns = [
#     path("polls/", PollList.as_view(), name="polls_list"),
#     path("polls/<int:pk>/", PollDetail.as_view(), name="polls_detail"),
#
#     path("polls/<int:pk>/choices/", ChoiceList.as_view(), name="choice_list"),  # for showing choice list by individual poll
#     path("polls/<int:pk>/choices/<int:choice_pk>/vote/", CreateVote.as_view(), name="create_vote"),
#
#     path("users/", UserCreate.as_view(), name="user_create"),
#     path("login/", LoginView.as_view(), name="login"),
# ]
#
# urlpatterns += router.urls

pollsapi/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers
from quickstart import views

router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'group', views.GroupViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('', include('snippets.urls')),
    # path('', include('quickstart.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Poll(models.Model):
    question = models.CharField(max_length=100)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question


class Choice(models.Model):
    poll = models.ForeignKey(Poll, related_name='choices', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Vote(models.Model):
    choice = models.ForeignKey(Choice, related_name='votes', on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    voted_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("poll", "voted_by")

polls/views.py
from django.http import JsonResponse, HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.views import generic

from polls.models import Poll, Choice, Vote


# Create your views here.


def polls_list(request):
    MAX_OBJECTS = 20
    polls = Poll.objects.all()[:MAX_OBJECTS]
    data = {"results": list(polls.values("question", "created_by__username", "pub_date"))}
    return JsonResponse(data)


def polls_detail(request, pk):
    poll = get_object_or_404(Poll, pk=pk)
    data = {"results": {
        "question": poll.question,
        "created_by": poll.created_by.username,
        "pub_date": poll.pub_date
    }}
    return JsonResponse(data)


def index(request):
    latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
    # output = ', '.join([q.question for q in latest_poll_list])
    # return HttpResponse(output)
    context = {'latest_poll_list': latest_poll_list}
    return render(request=request, template_name='polls/index.html', context=context)


def detail(request, poll_id):
    # return HttpResponse("You're looking at question %s." % poll_id)
    # try:
    #     poll = Poll.objects.get(pk=poll_id)
    # except Poll.DoesNotExist:
    #     raise Http404("Question does not exist")
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/detail.html', {'poll': poll})


def results(request, poll_id):
    # response = "You're looking at the results of question %s."
    # return HttpResponse(response % poll_id)
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Poll.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'


def vote(request, poll_id):
    # return HttpResponse("You're voting on question %s." % poll_id)
    poll = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = poll.choices.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'poll': poll,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.vote += 1
        selected_choice.save()
        # vote = Vote.objects.create(poll_id=poll.id, choice_id=selected_choice, voted_by=poll.created_by)
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(poll.id,)))

templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Poll Detail</title>
</head>
<body>
    {% comment %}<h1>{{ poll.question }}</h1>
    <ul>
        {% for choice in poll.choices.all %}
            <li>{{ choice.choice_text }}</li>
        {% endfor %}
    </ul>{% endcomment %}
    <form action="{% url 'polls:vote' poll.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ poll.question }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in poll.choices.all %}
                <input type="radio" name="choice" id="choices{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choices{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>
</html>

templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Poll List</title>
</head>
<body>
    {% if latest_poll_list %}
        <ul>
            {% for question in latest_poll_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>
</html>

templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ poll.question }}</h1>

    <ul>
        {% for choice in poll.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.vote }} vote{{ choice.vote|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' poll.id %}">Vote again?</a>
</body>
</html>